### ISSUE TITLE
bit.js process should exit with an error code if build failed

### ISSUE THREAD

**Issue by jcward** [hipponot/bit#10]
Most build tools exit with an error code >0 if the build fails. Therefor, this command `bit.js build && echo "ok"` should not echo "ok" in this case:

![image](https://user-images.githubusercontent.com/2192439/131160209-3acf8cab-2246-49ef-ae2d-ed7048176260.png)

**Comment by skilgoreT** [comment]
fixed and added` fail_sets_status_code` test case
