### ISSUE TITLE
Progress bars hide warnings

### ISSUE THREAD

**Issue by jcward** [hipponot/bit#11]
I love the progress bars, but it seems to "clear the screen" right before drawing them, which hides any warnings above that point. Although this could be related to #12  wherein I'd prefer warnings to fail more often.

**Comment by skilgoreT** [comment]
base_cmd has the static on_before_construct which is in essence a static initialization that runs before builder construction - in the case of build it ensure the progress bar is docked before any other output

**Comment by skilgoreT** [comment]
bit will dump the forked log file from any builder that fails
