### ISSUE TITLE
Bit warnings - some opinions

### ISSUE THREAD

**Issue by jcward** [hipponot/bit#12]
I see warnings from time to time, like this:

![image](https://user-images.githubusercontent.com/2192439/131161069-ce23943c-f025-4f93-9d58-027f7a12db6b.png)

I have a few opinions about this:

- Running yarn build:schema is what a bit developer would do to fix the issue. As a client of bit, I probably just made a typo.
- There's a lot of info here. As a client of bit, I just need a couple of those lines - specifically, steps[0] doesn't support property `nothing` (likely a typo / copy-paste error)
- This is a warning and the build continues... I think this should fail / exit. If I made a typo in my bit.yaml, my build is broken. It should not continue (which is exacerbated by #11)

**Comment by skilgoreT** [comment]
<pre><font color="#729FCF">INFO: Writing logs to /tmp/tmp-1207509-PS9ZluDR2Jeg, keep_logs is false</font>
<font color="#729FCF">INFO: Computing Dependency Graph</font>
<font color="#C4A000">WARN: /home/skelly/dev/pixijs-example/projects/test-app/bit.yaml failed schema</font>
<font color="#C4A000">validation</font>
<font color="#C4A000">WARN: data/steps/0 must NOT have additional properties</font>
<font color="#C4A000">WARN: [</font>
<font color="#C4A000">  {</font>
<font color="#C4A000">    &quot;params&quot;: {</font>
<font color="#C4A000">      &quot;additionalProperty&quot;: &quot;nothing&quot;</font>
<font color="#C4A000">    },</font>
<font color="#C4A000">    &quot;message&quot;: &quot;must NOT have additional properties&quot;</font>
<font color="#C4A000">  }</font>
<font color="#C4A000">]</font>
<font color="#C4A000">WARN: If this was not a typo and you need to update the schema, please update the</font>
<font color="#C4A000">ShellCmdBuilder interface in builders/schema and run &apos;yarn build:schema&apos;</font>
<font color="#EF2929"><b>ERROR: Aborting becuase invalid schema and --strict</b></font>
</pre>
