### ISSUE TITLE
Change in bit.yaml should invalidate .last_build.json cache

### ISSUE THREAD

**Issue by jcward** [hipponot/bit#22]
If bit.yaml changes, then I believe the last build result (cached) should be considered invalid (e.g. ignore / remove .last_build.json).

Perhaps via mtime / newer timestamp on bit.yaml, or store bit.yaml content hash in .last_build.json

**Comment by skilgoreT** [comment]
@jcward I though I had this one fixed with #13 - test case is passing

<pre><span style="background-color:#4E9A06"><font color="#000000"><b> PASS </b></font></span> <font color="#00AA00">test/unit/</font><b>build.test.ts</b>
  Test bit build
    <font color="#4E9A06">✓</font> bit_yaml_change_should_rebuild (719 ms)
 </pre>

do you have a counter example I can poke at ?

**Comment by jcward** [comment]
Hmm, I think I must have been using an out-of-date bit. I swear I had updated, but I can't repro it now. Closing.
