### ISSUE TITLE
Build failed, but no output

### ISSUE THREAD

**Issue by jcward** [hipponot/bit#4]
Isn't bit supposed to print the stdout+stderr if a build step fails? This one was a shell command builder.

![image](https://user-images.githubusercontent.com/2192439/131063602-c60ec777-8360-4c4e-9e94-3fd03ff34fa8.png)

**Comment by jcward** [comment]
This is the current blocker for using bit from pixijs-example -- it swallows the build error messages, which a dev needs to see to know what to fix.

Same issue in watch mode, btw:

![image](https://user-images.githubusercontent.com/2192439/131394816-f8cae9d3-4e3c-417e-b644-7e53d3071216.png)

**Comment by skilgoreT** [comment]
failed dependnecies now cancel the build and print a status highlighting the failed project 

![image](https://user-images.githubusercontent.com/560255/131564651-e1b333ec-a2a0-457d-96bd-7ff35dc4b3ce.png)

**Comment by skilgoreT** [comment]
Added rebuilt flag which is the result of the skipped | required logic

**Comment by skilgoreT** [comment]
added test case
