### ISSUE TITLE
Build fails, next build is skipped

### ISSUE THREAD

**Issue by jcward** [hipponot/bit#5]
When a build fails, the `.last_build.json` is still written, and so the next build is skipped with a "status true":

https://user-images.githubusercontent.com/2192439/131063990-25a7fb8e-886a-4e29-9d39-ac775c86571a.mp4

**Comment by skilgoreT** [comment]
fixed and added test case `- last_failed_should_not_skip`
<pre>──── Build Progress ────────────────────────────────────────────────────────────────────────────────────────────────────────────────
build_fails:6ad1ff6d: <font color="#3465A4">████████████████████ </font>                     50% | 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
<font color="#729FCF">INFO: Computing Dependency Graph</font>
<font color="#729FCF">INFO: Build Starting</font>
<font color="#EF2929"><b>ERROR: ShellRunner, name: build_fails error: Command failed: false</b></font>
<font color="#729FCF">INFO: Attempting gracefull shutdown</font>
<font color="#729FCF">INFO: Build Status</font>
<font color="#555753">┌────────────────────┬──────────┬──────────┬───────────────┬───────────────┬───────────────┐</font>
<font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>widget</b></font><font color="#CC0000">             </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>succeed</b></font><font color="#CC0000">  </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>duration</b></font><font color="#CC0000"> </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>skipped</b></font><font color="#CC0000">       </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>required</b></font><font color="#CC0000">      </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>rebuilt</b></font><font color="#CC0000">       </font><font color="#555753">│</font>
<font color="#555753">├────────────────────┼──────────┼──────────┼───────────────┼───────────────┼───────────────┤</font>
<font color="#555753">│</font> gchild2            <font color="#555753">│</font> <font color="#8AE234"><b>true</b></font>     <font color="#555753">│</font> 0.0      <font color="#555753">│</font> true          <font color="#555753">│</font> false         <font color="#555753">│</font> false         <font color="#555753">│</font>
<font color="#555753">├────────────────────┼──────────┼──────────┼───────────────┼───────────────┼───────────────┤</font>
<font color="#555753">│</font> build_fails        <font color="#555753">│</font> <font color="#EF2929"><b>false</b></font>    <font color="#555753">│</font> 0.1      <font color="#555753">│</font> false         <font color="#555753">│</font> false         <font color="#555753">│</font> <font color="#EF2929"><b>true</b></font>          <font color="#555753">│</font>
<font color="#555753">└────────────────────┴──────────┴──────────┴───────────────┴───────────────┴───────────────┘</font>
</pre>
